### ISSUE TITLE
Could not find a version that satisfies the requirement gl3w_gen

### ISSUE THREAD

**Issue by donno2048** [podgorskiy/bimpy#34]
when running `python setup.py install` on window10 with python 3.7 and 3.8 with pip 10.0 and 20.2 I get the following error:
```python
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    from gl3w import gl3w_gen
ImportError: cannot import name 'gl3w_gen' from 'gl3w' (unknown location)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    import gl3w_gen
ModuleNotFoundError: No module named 'gl3w_gen'
```

**Comment by donno2048** [comment]
I cloned gl3w to bimpy directory and now this is working...
