### ISSUE TITLE
Can't pip install bimpy on raspberry pi os :(

### ISSUE THREAD

**Issue by UnexpectedMaker** [podgorskiy/bimpy#41]
I can't get bimpy to pip install .... keep getting the following error:

```$pip install bimpy
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting bimpy
  Using cached https://files.pythonhosted.org/packages/59/10/fa47d72afbea9205804b96f3f13f56f6da0297837c05305d44776c3ebdf8/bimpy-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-install-tl2fmrev/bimpy/setup.py", line 47, in <module>
        from libs.gl3w import gl3w_gen
    ImportError: cannot import name 'gl3w_gen' from 'libs.gl3w' (unknown location)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-tl2fmrev/bimpy/setup.py", line 50, in <module>
        import gl3w_gen
    ModuleNotFoundError: No module named 'gl3w_gen'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-tl2fmrev/bimpy/```

I even built gl3w from source but still no good as bumpy is supposed to ship with it's own gl3w built in.

Ay ideas?

Python 3.7.3 (also tried 3.9.0) and Raspbian version: 10.8

**Comment by UnexpectedMaker** [comment]
I ended up just cloning and building from source - but pip installing would have been much nicer.

**Comment by ChDiego** [comment]
I also have the same problem:
Traceback (most recent call last):
  File "F:\pythonCode\bimpy\setup.py", line 47, in <module>
    from libs.gl3w import gl3w_gen
ImportError: cannot import name 'gl3w_gen' from 'libs.gl3w' (unknown location)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\pythonCode\bimpy\setup.py", line 50, in <module>
    import gl3w_gen
ModuleNotFoundError: No module named 'gl3w_gen'

The computer has Visual C++ 2015 installed

**Comment by antonnes** [comment]
Same problem as well, happening both on Windows and and Kubuntu 22.04

**Comment by tconnard** [comment]
This isn't an OS issue this is an issue with the source package on pypi being broken and not including the gl3w_gen.py script.

**Comment by theguyinthe-box** [comment]
use a virtual environment with python version set to 3.8, this fixes all issues.
